/* eslint-disable @typescript-eslint/no-unused-vars */

export const menus = [
  {
    id: 1,
    name: "Dry Curry",
    ingredient: "Pork",
    rating: [1, 2, 3, 4],
    avgRating: 0,
    image: "",
  },
  {
    id: 2,
    name: "生姜焼き",
    ingredient: "Pork",
    rating: [1, 2, 3, 4],
    avgRating: 0,
    image: "",
  },
  {
    id: 3,
    name: "肉じゃが",
    ingredient: "Pork",
    rating: [2, 4, 4, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 4,
    name: "春巻き",
    ingredient: "Chicken",
    rating: [3, 3, 3, 4],
    avgRating: 0,
    image: "",
  },
  {
    id: 5,
    name: "チキン南蛮",
    ingredient: "Chicken",
    rating: [5, 5, 4, 3],
    avgRating: 0,
    image: "",
  },
  {
    id: 6,
    name: "油淋鶏",
    ingredient: "Chicken",
    rating: [2, 3, 4, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 7,
    name: "Beef Stew",
    ingredient: "Beef",
    rating: [2, 3, 5, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 8,
    name: "Steak",
    ingredient: "Beef",
    rating: [1, 2, 4, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 9,
    name: "牛丼",
    ingredient: "Beef",
    rating: [4, 4, 5, 3],
    avgRating: 0,
    image: "",
  },
  {
    id: 10,
    name: "鮭定食",
    ingredient: "Salmon",
    rating: [2, 4, 4, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 11,
    name: "Poke Bowl",
    ingredient: "Salmon",
    rating: [5, 5, 3, 2],
    avgRating: 0,
    image: "",
  },
  {
    id: 12,
    name: "Ahijo",
    ingredient: "Shrimp",
    rating: [3, 3, 4, 5],
    avgRating: 0,
    image: "",
  },
  {
    id: 13,
    name: "エビフライ",
    ingredient: "Shrimp",
    rating: [2, 3, 4, 4],
    avgRating: 0,
    image: "",
  },
];
